export const INVOPAY_SUBSCRIPTION_ABI = [
  {
    inputs: [
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "address", name: "payer", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "uint256", name: "period", type: "uint256" },
      { internalType: "string", name: "description", type: "string" },
    ],
    name: "createSubscription",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "subscriptionId", type: "bytes32" }],
    name: "paySubscription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "subscriptionId", type: "bytes32" }],
    name: "cancelByCreator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "subscriptionId", type: "bytes32" }],
    name: "cancelByPayer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "subscriptionId", type: "bytes32" }],
    name: "getSubscription",
    outputs: [
      {
        components: [
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "address", name: "tokenAddress", type: "address" },
          { internalType: "uint256", name: "period", type: "uint256" },
          { internalType: "uint256", name: "nextPaymentDue", type: "uint256" },
          { internalType: "uint256", name: "pausedAt", type: "uint256" },
          { internalType: "uint8", name: "status", type: "uint8" },
          { internalType: "uint256", name: "createdAt", type: "uint256" },
          { internalType: "uint256", name: "totalPayments", type: "uint256" },
          { internalType: "string", name: "description", type: "string" },
        ],
        internalType: "struct InvopaySubscription.Subscription",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "creator", type: "address" }],
    name: "getCreatorSubscriptions",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "payer", type: "address" }],
    name: "getPayerSubscriptions",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "subscriptionId", type: "bytes32" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "uint256", name: "feeAmount", type: "uint256" },
      { internalType: "bool", name: "isCreationFee", type: "bool" },
    ],
    name: "FeeCollected",
    type: "event",
  },
  {
    inputs: [
      { indexed: true, internalType: "bytes32", name: "subscriptionId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { internalType: "address", name: "payer", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "uint256", name: "period", type: "uint256" },
      { internalType: "uint256", name: "nextPaymentDue", type: "uint256" },
      { internalType: "string", name: "description", type: "string" },
    ],
    name: "SubscriptionCreated",
    type: "event",
  },
  {
    inputs: [
      { indexed: true, internalType: "bytes32", name: "subscriptionId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "payer", type: "address" },
      { indexed: true, internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "uint256", name: "nextPaymentDue", type: "uint256" },
      { internalType: "uint256", name: "totalPayments", type: "uint256" },
    ],
    name: "SubscriptionPaid",
    type: "event",
  },
  {
    inputs: [
      { indexed: true, internalType: "bytes32", name: "subscriptionId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { indexed: true, internalType: "address", name: "payer", type: "address" },
    ],
    name: "SubscriptionCancelledByCreator",
    type: "event",
  },
  {
    inputs: [
      { indexed: true, internalType: "bytes32", name: "subscriptionId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "payer", type: "address" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
    ],
    name: "SubscriptionCancelledByPayer",
    type: "event",
  },
  {
    inputs: [
      { indexed: true, internalType: "bytes32", name: "subscriptionId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { internalType: "uint256", name: "pausedAt", type: "uint256" },
    ],
    name: "SubscriptionPaused",
    type: "event",
  },
  {
    inputs: [
      { indexed: true, internalType: "bytes32", name: "subscriptionId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { internalType: "uint256", name: "newNextPaymentDue", type: "uint256" },
    ],
    name: "SubscriptionResumed",
    type: "event",
  },
  {
    inputs: [{ internalType: "bytes32", name: "subscriptionId", type: "bytes32" }],
    name: "pauseSubscription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "subscriptionId", type: "bytes32" }],
    name: "resumeSubscription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

